### PR TITLE
Calculator App:  Milestone 1

### PR DESCRIPTION
**Pull request by Davidosky007**
## Calculator app 
In this milestone 
* react was created using npx create-react-app my app --use-npm
* the necessary code linters were set up
* prop-types and big.js were installed
* Heroku was used to host this project

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @Davidosky007  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well by adding `prop-types` and `big.js`, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**1.** Kindly update your live demo link with the codebase, the live link seems different from the codebase.
**2.** Always double-check your commit message for typo.
**3.** Kindly fix the screenshot in your README file.

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi @Davidosky007   :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

# Status: Changes Required! ♻️ 

**1. Apparently you commented out the screenshot, keep in mind you will have to add it once you get to milestone 5. 
2. For some reason it doesn't look like you have worked on the live demo link. kindly double-check.
It would be nice if you could share a screenshot of both the live demo and local.**

Kindly let me know if I'm missing something on this PR, drop a comment, thanks

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by Davidosky007** [comment]
> ## Hi @Davidosky007 👏
> **Great work making `almost` all the necessary corrections from the previous review.**
> 
> # Status: Changes Required! ♻️
> **1. Apparently you commented out the screenshot, keep in mind you will have to add it once you get to milestone 5. 2. For some reason it doesn't look like you have worked on the live demo link. kindly double-check. It would be nice if you could share a screenshot of both the live demo and local.**
> 
> Kindly let me know if I'm missing something on this PR, drop a comment, thanks
> 
> ### ♻️ Kindly re-submit for review after making all those changes 🙂 Thumps -up await you.....
> **Best,**
> 
> **Oluwaseun Bello**
> **_Slack Handle - @sean bellom_**

Clone and check my project view is the same as the live demo

**Review by bellom — APPROVED** [review]
## Hi @Davidosky007  :clap: 

**Great work making all the necessary corrections from the previous review**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
